name: Mirror FreshRSS

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch FreshRSS feed
        run: curl -s "$FEED_URL" -o events.xml
        env:
          FEED_URL: ${{ secrets.FEED_URL }}

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add events.xml
          git diff --quiet || git commit -m "update"

      - name: Push updates
        run: git push
